
language: node_js
node_js:
  - 8
script: npm install
deploy:
- provider: azure_web_apps
  username: $AZURE_WA_USERNAME
  password: $AZURE_WA_PASSWORD
  site: fitologiabackend
  slot: fitologiabackend
  verbose: true
  on:
    branch: master
